### PR TITLE
fix #10: allow https in image url

### LINKED ISSUE #10: HTTPS url
The url generated for images will be `http://` regardless.

I think a solution might be replacing the `URL::asset` calls in the facade with the `url()` helper, that should take into account current protocol, so if the user is browsing while in https the image will be resolved as https too.

What do you think?

### PR DESCRIPTION
**Pull request by brazorf**
I've currently tested this in L5.1

### CODE REVIEW

**Comment by markcameron** [comment]
Thanks for this, need to look at it properly, because `url()` won't work either, need to use `url_secure()` for https, But that forces https, which doesn't help when not running https.

**Comment by brazorf** [comment]
I think url() automatically takes into account the current user protocol, didnt check the source myself but i am using this solution in a live environment and it works without issues.

**Comment by markcameron** [comment]
Yeah, I've added a version to the 3.0 branch `3.0.x-dev` in composer if you want to give it a try, I run a check on the laravel `Illuminate\Http\Request` object call to `secure()` to check if we're on HTTPS and call `url()` or `url_secure()` accordingly.

Tried it on one of my sites and works. give it a go if you wish. I'm having another issue on another site, but that appears to be down to the nginx config forcing `$SERVER['HTTPS']` to off.

**Comment by brazorf** [comment]
Dont know if you can rely on the framework `secure` implementations: if you are running an artisan command there will be no protocol set, so i think you should rely on a config value, what do you think?

**Comment by markcameron** [comment]
Yeah I didn't think about  an artisan command, but that's less of an issue. I just don't like the idea of having to tell it that it is HTTPS or not through a config file, which will in the end require setting something in you .env so that you can control it between dev and production. Seems like a lot over overhead.

**Comment by brazorf** [comment]
Well not much of an overhead in fact, it's just a boolean setting that can be defaulted. What we do with this pull request?

**Comment by markcameron** [comment]
In `3.0.10`

**Pull request closed without merging**
